version: "3"
services:
  springapp:
    build: .
    container_name: erf-docker
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/erf
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
  mail:
    image: maildev/maildev
    container_name: maildev
    restart: always
    environment:
      RELAY_HOST: maildev
      RELAY_PORT: 1025
    ports:
      - '1025:1025'
      - '8025:8025'

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=erf
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5000:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata: